import {
  StyleSheet,
  Text,
  View,
  SafeAreaView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
} from "react-native";
import React from "react";
import { useRouter } from "expo-router";
import { LinearGradient } from "expo-linear-gradient";
import { useAuth } from "../../context/AuthContext";
import { MaterialIcons } from "@expo/vector-icons";

const Home = () => {
  const router = useRouter();
  const { isAuthenticated, initialized, user } = useAuth();

  const handleGetStarted = () => {
    if (isAuthenticated) {
      // If authenticated, go to upload page
      router.push("/upload");
    } else {
      // If not authenticated, go to login page
      router.push("/auth/login");
    }
  };

  const handleAdminAccess = () => {
    if (!isAuthenticated) {
      Alert.alert("Login Required", "Please login to access admin features.");
      router.push("/auth/login");
      return;
    }

    // Check if user has admin email
    if (user?.email === "22z214@psgtech.ac.in") {
      router.push("/admin");
    } else {
      Alert.alert(
        "Access Denied",
        "You don't have permission to access admin features."
      );
    }
  };

  if (!initialized) {
    return (
      <SafeAreaView style={styles.safeArea}>
        <LinearGradient
          colors={["#111", "black"]}
          style={[styles.container, styles.loadingContainer]}
        >
          <ActivityIndicator size="large" color="#fff" />
        </LinearGradient>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safeArea}>
      <LinearGradient colors={["#111", "black"]} style={styles.container}>
        <View style={styles.content}>
          <Text style={styles.title}>AudioFinder</Text>

          <Text style={styles.description}>
            AudioFinder helps you distinguish between real and fake audio.
            Upload your audio files or speak directly to get an instant
            analysis. Detect if the audio is authentic or generated by AI with
            our advanced algorithms.
          </Text>

          <TouchableOpacity style={styles.button} onPress={handleGetStarted}>
            <Text style={styles.buttonText}>Get Started</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.adminButton}
            onPress={handleAdminAccess}
          >
            <MaterialIcons name="admin-panel-settings" size={18} color="#fff" />
            <Text style={styles.adminButtonText}>Admin Dashboard</Text>
          </TouchableOpacity>
        </View>
      </LinearGradient>
    </SafeAreaView>
  );
};

export default Home;

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 20,
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 20,
    textAlign: "center",
  },
  description: {
    fontSize: 18,
    color: "#ccc",
    textAlign: "center",
    marginBottom: 30,
  },
  button: {
    backgroundColor: "#333",
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 8,
    width: "60%",
    marginTop: 20,
  },
  buttonText: {
    fontSize: 18,
    color: "#fff",
    textAlign: "center",
  },
  adminButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#444",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 15,
    borderWidth: 1,
    borderColor: "#666",
  },
  adminButtonText: {
    fontSize: 14,
    color: "#fff",
    marginLeft: 8,
  },
  loadingContainer: {
    justifyContent: "center",
  },
});
